name: Realse

on:
  push:
    tags:
    - 'v*'

env:
  SOLUTION_FILE_PATH: metamod/lagcompensator
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build-win32:
    runs-on: windows-latest

    steps:    
    - name: Git Clone Metamod
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: hzqst/metamod-fallguys
        path: metamod
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/lagcompensator
        path: metamod/lagcompensator

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: metamod/build/addons/metamod/dlls/lagcompensator.dll
          dest: lagcompensator-windows-x86.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: lagcompensator-${{ github.ref }}
          files: |
            lagcompensator-windows-x86.zip
    
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Build Enviroment
      uses: ConorMacBride/install-package@v1
      with:
        apt: make build-essential gcc gcc-multilib g++-multilib
          
    - name: Git Clone Metamod
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: hzqst/metamod-fallguys
        path: metamod
    
    - name: Git Clone This
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: DrAbcOfficial/lagcompensator
        path: metamod/lagcompensator

    - name: Build
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: make OPT=opt install

    - name: Zipping All
      uses: vimtor/action-zip@v1
      with:
          files: metamod/build/addons/metamod/dlls/lagcompensator.so
          dest: lagcompensator-ubuntu-i386.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          name: lagcompensator-${{ github.ref }}
          files: |
            lagcompensator-ubuntu-i386.zip
